Repository daangn/KarrotFlex, pull requests merged in 2021-12, with the labels that each got.

#6 Fix FlexInset bug & add snapshot test
  Example/KarrotFlex.xcodeproj/project.pbxproj
  Example/KarrotFlex/ViewController.swift
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_infinity_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_inset_with_UIEdgeInsets@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_horizontal_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_inset_position@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_vertical_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_infinity_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_inset_with_UIEdgeInsets@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_horizontal_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_inset_position@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_vertical_inset@3x.png
  Example/Tests/FlexInsetTests.swift
  Sources/KarrotFlex/FlexLayout+Sugar.swift
Labels: bug

#7 Remove KarrotFlex+Sugar
  Example/KarrotFlex.xcodeproj/project.pbxproj
  Example/KarrotFlex/Base.lproj/Main.storyboard
  Example/KarrotFlex/FlexCenterCell.swift
  Example/KarrotFlex/FlexVStackCell.swift
  Example/KarrotFlex/Images.xcassets/Contents.json
  Example/KarrotFlex/Images.xcassets/daangnbot.imageset/Contents.json
  Example/KarrotFlex/Images.xcassets/daangnbot.imageset/daangnbot.png
  Example/KarrotFlex/ViewController.swift
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexCenterTests/test_center_X@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexCenterTests/test_center_XY@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexCenterTests/test_center_Y@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_alignItems_baseline@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_alignItems_center@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_alignItems_end@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_alignItems_stretch@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_default@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_justifyContent_center@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_justifyContent_end@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_justifyContent_space_around@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexHStackTests/test_justifyContent_space_between@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_infinity_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_all_inset_with_UIEdgeInsets@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_horizontal_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_inset_position@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_vertical_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_infinity_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_all_inset_with_UIEdgeInsets@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_horizontal_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_inset_position@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexInsetsTests/test_view_vertical_inset@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexOverlayTests/test_nested_centering_overlay_from_large_to_small_rect@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexOverlayTests/test_nested_centering_overlay_from_small_to_large_rect@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexOverlayTests/test_nested_overlay_from_large_to_small_rect@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexOverlayTests/test_nested_overlay_from_small_to_large_rect@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_alignItems_center@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_alignItems_end@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_alignItems_stretch@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_default@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_justifyContent_center@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_justifyContent_end@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_justifyContent_space_around@3x.png
  Example/KarrotFlexTests/ReferenceImages_64/KarrotFlex_Tests.FlexVStackTests/test_justifyContent_space_between@3x.png
  Example/Podfile.lock
  Example/Tests/FlexCenterTests.swift
  Example/Tests/FlexHStackTests.swift
  Example/Tests/FlexInsetTests.swift
  Example/Tests/FlexOverlayTests.swift
  Example/Tests/FlexVStackTests.swift
  README.md
  Sources/KarrotFlex/Exported.swift
  Sources/KarrotFlex/FlexCenter.swift
  Sources/KarrotFlex/FlexHStack.swift
  Sources/KarrotFlex/FlexItem.swift
  Sources/KarrotFlex/FlexLayout+Sugar.swift
  Sources/KarrotFlex/FlexOverlay.swift
  Sources/KarrotFlex/FlexSpacer.swift
  Sources/KarrotFlex/FlexVStack.swift
  res/daangnbot.imageset/daangnbot.png
Labels: enhancement

#8 Support a StackLayout with direction & register method
  Example/KarrotFlex.xcodeproj/project.pbxproj
  Example/KarrotFlex/BaseViewController.swift
  Example/KarrotFlex/FlexAnimationCell.swift
  Example/KarrotFlex/FlexAnimationViewController.swift
  Example/KarrotFlex/ViewController.swift
  Example/Podfile
  Example/Podfile.lock
  README.md
  Sources/KarrotFlex/Flex+Extension.swift
  Sources/KarrotFlex/FlexStack.swift
Labels: enhancement, in dependent

#11 add PinLayout
  Example/KarrotFlex.xcodeproj/project.pbxproj
  Example/Podfile.lock
  KarrotFlex.podspec
  Package.swift
  Sources/KarrotFlex/Exported.swift
Labels: enhancement

#12 Fix SPM import Error
  Sources/KarrotFlex/FlexCenter.swift
  Sources/KarrotFlex/FlexItem.swift
  Sources/KarrotFlex/FlexSpacer.swift
Labels: bug
